http://localhost:3001/api/persons/

###
http://localhost:3001/api/persons/6630da6293e058e5abc8c32a




###

http://localhost:3001/info/

###
# this is a separator 

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "oy", 
    "number": "4545454454"
}

###
PUT http://localhost:3001/api/persons/6630df512b124286514fbe20
Content-Type: application/json

{
    "name": "oy put 2", 
    "number": "4545454454"
}


###
# this is a separator 

DELETE  http://localhost:3001/api/persons/6630dfc8ae5eac1ec939a62d
Content-Type: application/json




###
https://phonebook-pnmx.onrender.com/api/persons/


###
POST https://phonebook-pnmx.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "oye", 
    "number": "4545454454"
}