http://localhost:3001/api/persons/

###
http://localhost:3001/api/persons/6630d628beab9536f62ab82c




###

http://localhost:3001/info/

###
http://localhost:3001//user-ip/

###
# this is a separator 

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "oyrest", 
    "number": "92222222222222"
}

###
PUT http://localhost:3001/api/persons/6631d3fdde63443f247a0f47
Content-Type: application/json

{
    "name": "oyrest", 
    "number": "222222222222"
}


###
# this is a separator 

DELETE  http://localhost:3001/api/persons/6630dfc8ae5eac1ec939a62d
Content-Type: application/json




###
https://phonebook-pnmx.onrender.com/api/persons/


###
POST https://phonebook-pnmx.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "oye", 
    "number": "4545454454"
}